# Generated by Django 5.0.6 on 2024-06-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdottax', '0002_remove_mail_image_mail_email_mail_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='message',
            field=models.TextField(default='this is simple message'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='mobile_number',
            field=models.CharField(default='', help_text='Enter your mobile number', max_length=20, unique=True),
        ),
    ]
