# Generated by Django 5.0.6 on 2024-06-26 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdottax', '0003_mail_message_alter_mail_mobile_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail',
            old_name='mobile_number',
            new_name='mobile',
        ),
    ]
