# Generated by Django 5.0.6 on 2024-06-27 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdottax', '0004_rename_mobile_number_mail_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='mobile',
            field=models.CharField(default='', help_text='Enter your mobile number', max_length=16, unique=True),
        ),
    ]
