# Generated by Django 5.0.6 on 2024-07-07 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdottax', '0005_alter_mail_mobile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mail',
        ),
    ]
