# Generated by Django 5.0.6 on 2024-12-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='email',
            field=models.EmailField(default='abxc@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='mail',
            name='mobile',
            field=models.CharField(blank=True, help_text='Enter your mobile number', max_length=16),
        ),
    ]
